service: starlit

provider:
  name: aws
  runtime: python2.7

functions:
  starlit:
    handler: handler.main
    events:
      - sqs:
        arn: arn:aws:sqs:us-east-1:110303772622:starlit-pending-crawls20181215040408288200000001
        batchSize: 1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
