service: starlit

provider:
  name: aws
  runtime: python2.7

package:
  exclude:
    - .terraform/**
    - node_modules/**
    - venv/**
functions:
  starlit:
    handler: handler.main
    reservedConcurrency: 1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
